CREATE DATABASE BIBLIOTECA;
USE BIBLIOTECA;

CREATE TABLE AUTORES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    NACIONALIDADE VARCHAR(50),
    DATANASCIMENTO DATE    
);

CREATE TABLE LIVROS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(50),
    ANOPUBLICACAO VARCHAR(4),
    AUTORESID INT,
    FOREIGN KEY (AUTORESID) REFERENCES AUTORES(ID)
);

INSERT INTO AUTORES (NOME, NACIONALIDADE, DATANASCIMENTO) VALUES ("AUTOR1", "BRASILEIRO", "2024-10-28");
INSERT INTO AUTORES (NOME, NACIONALIDADE, DATANASCIMENTO) VALUES ("AUTOR2", "BRASILEIRO", "2020-10-28");
INSERT INTO LIVROS (TITULO, ANOPUBLICACAO, AUTORESID) VALUES ("TITULO1", "2020", 1);
INSERT INTO LIVROS (TITULO, ANOPUBLICACAO, AUTORESID) VALUES ("TITULO2", "2021", 1);
INSERT INTO LIVROS (TITULO, ANOPUBLICACAO, AUTORESID) VALUES ("TITULO3", "2021", 2);

SELECT A.NOME, L.TITULO
FROM AUTORES A
LEFT JOIN LIVROS L ON A.ID = L.AUTORESID;